version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - /tools/format-playlist
      - /tools/id3-sanitizer
    schedule:
      interval: monthly
    groups:
      go-dependencies:
        patterns:
          - "*"
      go-security:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
      github-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
